# Generated by Django 5.2.8 on 2025-11-18 07:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=255, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Название товара')),
                ('summary', models.TextField(help_text='Введите описание товара', verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену товара', max_digits=10, verbose_name='Цена товара')),
                ('is_published', models.BooleanField(help_text='Выберите опубликовать или нет', verbose_name='Публикация')),
                ('is_digital', models.BooleanField(default=False, help_text='Выберите электронный источник или нет', verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug продукта')),
                ('image', models.ImageField(upload_to='content_images/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель контента')),
                ('category', models.ManyToManyField(help_text='Выберите категорию товара', to='ContentApp.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ContentApp.content', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный товар',
                'verbose_name_plural': 'Избранные товары',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], help_text='Выберите оценку от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(blank=True, help_text='Введите комментарий к оценке', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания оценки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления оценки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор оценки')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ContentApp.content', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-created_at'],
                'unique_together': {('content', 'author')},
            },
        ),
    ]
