# Generated by Django 5.2.8 on 2025-11-19 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'За'), (-1, 'Против'), (0, 'Воздержался')], default=0, help_text='Голос за или против категории', verbose_name='Голос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentApp.category', verbose_name='Категория')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_votes', to='ContentApp.content', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Голос за категорию',
                'verbose_name_plural': 'Голоса за категории',
                'ordering': ['-created_at'],
                'unique_together': {('content', 'category', 'user')},
            },
        ),
    ]
